# --- Site Info ---
title: The Axiom
tagline: Daily System Design Learning
description: My automated journey to becoming an Expert Architect.
url: "https://coderpratik11.github.io" 
baseurl: "/the-axiom" 

# --- Theme Settings (CHANGED) ---
theme: jekyll-theme-chirpy  # Use 'theme', not 'remote_theme'

# --- Automation Settings ---
future: true
timezone: Asia/Kolkata 
lang: en
paginate: 10
theme_mode: light

# --- Plugins ---
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-include-cache
